-- Create Tables
START TRANSACTION;

-- Create the 'users' table
CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL,
  active BOOLEAN NOT NULL DEFAULT FALSE
);
-- set owner
ALTER TABLE users OWNER TO sundowner_@DBTAGLOWERCASE;
-- index
CREATE INDEX idx_users_username ON users(username);

-- Create the 'authorities' table for user roles
CREATE TABLE IF NOT EXISTS authorities (
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  authority VARCHAR(255) NOT NULL,
  PRIMARY KEY (user_id, authority)
);
-- set owner
ALTER TABLE authorities OWNER TO sundowner_@DBTAGLOWERCASE;


-- Create the 'spots' table
CREATE TABLE IF NOT EXISTS spots (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  type VARCHAR(255) NOT NULL CHECK (type IN ('SUNSET', 'SUNRISE')) DEFAULT 'SUNSET',
  location geometry(Point, 4326) NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  added_by_id BIGINT REFERENCES users(id) NOT NULL,
  added_at TIMESTAMPTZ NOT NULL,
  transport VARCHAR(255)[] NOT NULL CHECK (transport <@ ARRAY['BY_FOOT', 'CAR', 'BIKE', 'PUBLIC_TRANSPORT']::VARCHAR(255)[]),
  status VARCHAR(255) NOT NULL CHECK (status IN ('DRAFT', 'PENDING', 'CONFIRMED', 'REJECTED', 'ARCHIVED'))
);
-- set owner
ALTER TABLE spots OWNER TO sundowner_@DBTAGLOWERCASE;
-- index
CREATE INDEX idx_spots_location ON spots USING GIST (location);
CREATE INDEX idx_spots_status ON spots(status);

-- Create the 'spot_reviews' table
CREATE TABLE IF NOT EXISTS spot_reviews (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  spot_id BIGINT REFERENCES spots(id) NOT NULL,
  rated_by_id BIGINT REFERENCES users(id) NOT NULL,
  rating INTEGER CHECK (rating BETWEEN 0 AND 5) NOT NULL,
  comment TEXT
);
-- set owner
ALTER TABLE spot_reviews OWNER TO sundowner_@DBTAGLOWERCASE;
-- index
CREATE INDEX idx_spot_reviews_spot_id ON spot_reviews(spot_id);
CREATE INDEX idx_spot_reviews_rating ON spot_reviews(rating);

-- Create the 'photos' table
CREATE TABLE IF NOT EXISTS photos (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  spot_id BIGINT NOT NULL REFERENCES spots(id),
  review_id BIGINT REFERENCES spot_reviews(id),
  uploaded_by_id BIGINT REFERENCES users(id) NOT NULL,
  uploaded_at TIMESTAMPTZ NOT NULL,
  url TEXT NOT NULL
);
-- set owner
ALTER TABLE photos OWNER TO sundowner_@DBTAGLOWERCASE;
-- index
CREATE INDEX idx_photos_spot_id ON photos(spot_id);
CREATE INDEX id_photos_uploaded_at ON photos(uploaded_at);

-- Create the 'refresh_tokens' table
CREATE TABLE refresh_tokens IF NOT EXISTS  (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token TEXT NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
-- set owner
ALTER TABLE refresh_tokens OWNER TO sundowner_@DBTAGLOWERCASE;
-- index
CREATE INDEX idx_refresh_tokens_token ON refresh_tokens(token);

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO sundowner_@DBTAGLOWERCASE;

END;

