/**
 * Sundowner Service API
 * This is the API for the Sundowner Service.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Transfer object for a simple longitude and latitude coordinate.
 */
export interface CoordinateTO { 
    /**
     * The longitude of the coordinate.
     */
    lng: number;
    /**
     * The latitude of the coordinate.
     */
    lat: number;
}

