/**
 * Sundowner Service API
 * This is the API for the Sundowner Service.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoordinateTO } from './coordinateTO';


/**
 * Request body for creating a new sunset spot on the map.
 */
export interface CreateSpotRequest { 
    /**
     * The type of spot (e.g. sunrise or sunset)
     */
    type: CreateSpotRequest.TypeEnum;
    /**
     * The geographical coordinates of the sunset spot.
     */
    location: CoordinateTO;
    /**
     * A user-provided description of the spot (e.g., \'Quiet place with a great view over the valley\').
     */
    description?: string;
    /**
     * A list of recommended transport methods to reach the spot.
     */
    transport: Array<CreateSpotRequest.TransportEnum>;
}
export namespace CreateSpotRequest {
    export type TypeEnum = 'SUNSET' | 'SUNRISE';
    export const TypeEnum = {
        Sunset: 'SUNSET' as TypeEnum,
        Sunrise: 'SUNRISE' as TypeEnum
    };
    export type TransportEnum = 'BY_FOOT' | 'CAR' | 'BIKE' | 'PUBLIC_TRANSPORT';
    export const TransportEnum = {
        ByFoot: 'BY_FOOT' as TransportEnum,
        Car: 'CAR' as TransportEnum,
        Bike: 'BIKE' as TransportEnum,
        PublicTransport: 'PUBLIC_TRANSPORT' as TransportEnum
    };
}


