/**
 * Sundowner Service API
 * This is the API for the Sundowner Service.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoordinateTO } from './coordinateTO';


/**
 * Transfer object of the spot immediately shown on the map with the necessary details.
 */
export interface MapSpotTO { 
    /**
     * The ID of the element.
     */
    id: number;
    location: CoordinateTO;
    /**
     * The name given to the spot.
     */
    name: string;
    /**
     * The overall rating of the spot.
     */
    avgRating: number;
}

