/**
 * Sundowner Service API
 * This is the API for the Sundowner Service.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { MapSpotTO } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface GetPointsInViewRequestParams {
    minX: number;
    minY: number;
    maxX: number;
    maxY: number;
    limit?: number;
}


export interface SpotsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get the most relevant points of the provided map viewport.
     * Retrieves a list of points of interest (spots) located within the given bounding box and filtered based on zoom level and center coordinates.
* @param requestParameters
     */
    getPointsInView(requestParameters: GetPointsInViewRequestParams, extraHttpRequestParams?: any): Observable<Array<MapSpotTO>>;

}
