name: Sundowner CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  sundowner-service:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        ports:
          - 5433:5433
        env:
          POSTGRES_USER: sundowner_test
          POSTGRES_PASSWORD: SUNDOWNER_TEST
          POSTGRES_DB: sundowner_test_db
        options: >-
          --health-cmd pg_isready --health-timeout 10s

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Create Database
        working-directory: sundowner-service/data/src/main/resources/db
        run: |
          sed "s/%s/test/g" ./create_database.sql | psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --host localhost --port 5433 -f ./create_database.sql
        env:
          POSTGRES_USER: postgres

      - name: Create Tablespace
        working-directory: sundowner-service/data/src/main/resources/db
        run: |
          sed "s/%s/test/g" ./create_tablespace.sql | psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --host localhost --port 5433 -f ./create_tablespace.sql
        env:
          POSTGRES_USER: postgres

      - name: Create User
        working-directory: sundowner-service/data/src/main/resources/db
        run: |
          sed "s/%S/TEST/g" ./create_user.sql | sed "s/%s/test/g" ./create_user.sql | psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --host localhost --port 5433 --dbname "$POSTGRES_DB" ./create_user.sql
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: sundowner_test_db

      - name: Create Tables
        working-directory: sundowner-service/data/src/main/resources/db
        run: |
          sed "s/%s/test/g" ./create_tables.sql | psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --host localhost --port 5433 --dbname "$POSTGRES_DB" -f ./create_tables.sql
        env:
          POSTGRES_USER: sundowner_test
          POSTGRES_DB: sundowner_test_db

      - name: Initialize Data
        working-directory: sundowner-service/data/src/main/resources/db
        run: psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --host localhost --port 5433 --dbname "$POSTGRES_DB" -f ./initialize_data.sql
        env:
          POSTGRES_USER: sundowner_test
          POSTGRES_DB: sundowner_test_db

      - name: Build Sundowner Service
        working-directory: sundowner-service
        run: ./gradlew build

      - name: Test Sundowner Service
        working-directory: sundowner-service
        run: ./gradlew test

  sundowner-webapp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install node modules
        working-directory: sundowner-webapp
        run: npm install

      - name: Build Sundowner Webapp
        working-directory: sundowner-webapp
        run: ./node_modules/.bin/ng build

      - name: Test Sundowner Webapp
        working-directory: sundowner-webapp
        run: ./node_modules/.bin/ng test --watch=false

      - name: Upload Webapp Artifacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: sundowner-webapp-artifacts
          path: sundowner-webapp/dist/*
