---
name: Sundowner CI/CD
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  sundowner-service:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:17-master
        env:
          PGUSER: postgres
          PGPASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: temurin

      - name: Replace lowercase placeholders in SQL files 
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "@DBTAGLOWERCASE"
          replace: "test"
          include: "sundowner-service/data/src/main/resources/db/**"
          regex: false
          
      - name: Replace uppercase placeholders in SQL files 
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "@DBTAGUPPERCASE"
          replace: "TEST"
          include: "sundowner-service/data/src/main/resources/db/**"
          regex: false

      - name: Create User
        working-directory: sundowner-service/data/src/main/resources/db
        run: psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --host localhost --port 5433 -f ./create_user.sql
        env:
          POSTGRES_USER: postgres
          PGPASSWORD: postgres

      - name: Create Database
        working-directory: sundowner-service/data/src/main/resources/db
        run: psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --host localhost --port 5433 -f ./create_database.sql
        env:
          POSTGRES_USER: postgres
          PGPASSWORD: postgres

      - name: Create Extensions
        working-directory: sundowner-service/data/src/main/resources/db
        run: psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" --host localhost --port 5433 -f ./create_extensions.sql -d "$POSTGRES_DB"
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: sundowner_test_db
          PGPASSWORD: postgres

      - name: Create Tables
        working-directory: sundowner-service/data/src/main/resources/db
        run: psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" --host localhost --port 5433 -f ./create_tables.sql -d "$POSTGRES_DB"
        env:
          POSTGRES_USER: sundowner_test
          POSTGRES_DB: sundowner_test_db
          PGPASSWORD: SUNDOWNER_TEST

      - name: Build and Test Sundowner Service with JaCoCo Coverage
        working-directory: sundowner-service
        run: ./gradlew test jacocoTestReport --scan

      - name: Display JaCoCo Coverage Report
        working-directory: sundowner-service/build/reports/jacoco/test
        run: |
          echo "## JaCoCo Code Coverage Report"
          echo "### Line Coverage"
          line_coverage=$(grep -oP '<tfoot>.*?([0-9.]+)%.*?</tfoot>' index.html | grep -oP '([0-9.]+)%')
          echo "Line Coverage: $line_coverage"

  sundowner-webapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install node modules
        working-directory: sundowner-webapp
        run: npm install

      - name: Build Sundowner Webapp
        working-directory: sundowner-webapp
        run: ./node_modules/.bin/ng build --configuration=test

      - name: Lint Code
        working-directory: sundowner-webapp
        run: npm run lint

      - name: Test Sundowner Webapp
        working-directory: sundowner-webapp
        run: npm run test -- --coverage --watchAll=false

