name: Sundowner CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and test Sundowner Service
        working-directory: sundowner-service
        run: ./gradlew build integrationTest

      - name: Set up Node.js 23
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Build and test Sundowner Webapp
        working-directory: sundowner-webapp
        run: |
          npm install
          ng build --prod
          ng test --watch=false --browsers=ChromeHeadlessCI test run

      - name: Upload artifacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: sundowner-artifacts
          path: |
            sundowner-service/build/libs/*.jar
            sundowner-webapp/dist/*
